### ISSUE TITLE
support for peripheral membrane protein insertion

### ISSUE THREAD

**Issue by nlatorra** [drorlab/dabble#14]
Hi Robin,

I've tried to Dabble a peripheral membrane protein by simply aligning it to a peripheral membrane protein present in the OPM and feeding this through Dabble. Using certain z dimensions (specified by the user), I can get a system where my protein is indeed sitting at some distance below the membrane. However, when I visualize the periodic boxes, the boxes in the z dimension have large gaps between them, which I imagine should be filled with water but are instead a vacuum. I don't know how I didn't catch this earlier. I think this is what is causing my simulations to form 'micelle-like' membranes. Is there anything I can do to prevent this?

Than you!
Naomi

**Comment by Eigenstate** [comment]
Hmmm that is interesting. Can you slack me the path to your input files so
I can test a fix? I am super bored on a plane right now pls help

**Comment by nlatorra** [comment]
Yes, already sent!

________________________________

**Comment by Eigenstate** [comment]
Fixed with Commit efed353dd6bd06548329243db60c549b00460982
Dabble version >= 2.0.2
